export const LOWERCASE_LETTERS = 'abcdefghijklmnopqrstuvwxyz';
export const UPPERCASE_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
export const DIGITS = '0123456789';
export const HEX = '0123456789abcdef';
export const LITERAL = UPPERCASE_LETTERS + LOWERCASE_LETTERS + DIGITS;
export const LITERAL_LOWER = LOWERCASE_LETTERS + DIGITS;
export const LITERAL_UPPER = UPPERCASE_LETTERS + DIGITS;

export const alphabet = {
    DIGITS,
    HEX,
    LITERAL,
    LITERAL_LOWER,
    LITERAL_UPPER,
    LOWERCASE_LETTERS,
    UPPERCASE_LETTERS,
};
